[project]
name = "package-insights"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "docker>=7.1.0",
    "pytest>=8.4.2",
    "pytest-mock>=3.15.0",
    "pytest-timeout>=2.4.0",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["package_insights*"]
exclude = ["integration_tests*", "tests*"]
